# TODO support multiple nodes (doesn't work yet)
metal:
  children:
    masters:
      hosts:
        dev0: {ansible_host: 192.168.1.10}
        # dev1: {ansible_host: 192.168.1.11}
        # dev2: {ansible_host: 192.168.1.12}
    workers:
      hosts: {}
        # dev3: {ansible_host: 192.168.1.13}
