#!/bin/sh

export KUBECONFIG=./metal/kubeconfig.yaml

kubectl get applicationsets --namespace argocd
kubectl get applications --namespace argocd
kubectl get pods --all-namespaces
kubectl get ingress --all-namespaces